---
title: "POKEMON TAKIMI"
sidebar: false 
---

MUY665-İş Analitiği dersi Pokemın Takımı sayfamıza hoş geldiniz.

**Lütfen faaliyetlerimizi görmek için için bizi takipte kalın.**

## Takım Üyeleri

1.  [Susku UZUN](/takim/suskuuzun.qmd) (Raichu)

2.  [Enes Mert ACAR](/takim/enesmertacar.qmd) (Machoke)

3.  [Mertcan ÇALDAR](/takim/mertcancaldar.qmd) (Bulbasaur)

4.  [Çağla Hazal MÜVEZZİ](/takim/caglahazalmuvezzi.qmd) (Mew)

5.  [Bahadır AKGÜN](/takim/bahadırakgun.qmd) (Squirtle)

6.  [Süleyman ÖZDEMİR](/takim/suleymanozdemir.qmd) (Charmander)

## Proje Adı

MUY660-İş Analitiği iyileştirme çalışmaları (örnek)

## Proje Konusu

Örnek: Bu projede MUY660-İş Analitiği ders içeriğinin analitik yaklaşımlarla iyileştirilmesini hedefledik. Bu doğrultuda tüm üniversitelerdeki benzer derslerin verisini toplayarak bir veri seti oluşturduk Analiz için ........ yöntemleri kullanarak, ....... çalışmaları yaptık Sonuç olarak, MUY660-İş Analitiği dersinin dünyadaki tüm derslerden daha iyi olduğunu ve bu dersi aldığımız için çok mutlu olduğumuzu tespit ettik.

## Veri Seti Hakkında Özet Bilgi

## Sonuçlar

Burada key takeways verilmelidir. En az 3 en fazla 5 madde ile çarpıcı sonuçlar sunulmalıdır.
