---
title: "Çalışma 1"
---

## (a)

`{r} 1 + 1}`

## (b)

```{r}
ozel_ozet <- function(vec) { # Özel Özet Fonksiyonu
  #Ortalama, Medyan, Standart Sapma, Minimum ve Maksimum değerler değişkene atandı
  ozet_liste <- list(
    Ortalama = mean(vec),
    Medyan = median(vec),
    Standart_Sapma = sd(vec),
    Minimum = min(vec),
    Maksimum = max(vec)
  )
  return(ozet_liste)
}


# mtcars veri seti yüklendi
data(mtcars)

# Veri setinin sayısal sütunları al
sayisal_sutunlar <- sapply(mtcars, is.numeric)

# Her bir sayısal sütun için custom_summary fonksiyonunu uygula ve sonuçları yan yana yazdır
for (col in names(mtcars)[sayisal_sutunlar]) {
  ozet <- ozel_ozet(mtcars[[col]])
  cat("Araba Özellikleri:", col, "\n")
  cat("Ortalama:",  ozet$Ortalama, "\t \t")
  cat("Medyan:",sprintf("%.2f", round(ozet$Medyan,digits = 2)), "\t \t")
  cat("Standart Sapma:", round (ozet$Standart_Sapma, digits = 2), "\t \t")
  cat("Minimum:", sprintf("%.2f",ozet$Minimum), "\t \t")
  cat("Maksimum:", ozet$Maksimum, "\n")
  
  cat("------------------------------------------------------------------------------------------------------------","\n")
}



```

## (c)

```{r}
# İlk başta dslabs paketi yüklendi
library(dslabs)

# na_example veri seti yüklendi
data("na_example")

# Veri setinin içeriği NA değerleri ile birlikte gösterildi
na_example

# NA değerlerinin toplam sayısı bulundu
na_count <- sum(is.na(na_example))
cat("İlk durumda NA verilerinin adeti:", na_count, "\n")

# NA değerlerini 665 ile değiştirildi
updated_na_example <- na_example
updated_na_example[is.na(updated_na_example)] <- 665

# Na değerleri olmadan güncellenen veri seti kontrol edildi
updated_na_example

# Güncellenmiş veri setindeki NA değerlerinin toplam sayısı bulundu
updated_na_count <- sum(is.na(updated_na_example))

# Güncellenmiş veri setinde 665 numarası adetleri bulundu
num_665 <- sum(updated_na_example == 665)
cat("665 sayılarının adeti:", num_665, "\n")
cat("Son durumda NA verilerinin adeti:",updated_na_count)

```
